pipeline:
  identifier: Build_jhttp_1743110589737
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: cd
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: jhttpgithubtoken
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
                      echo "Contents of current directory:"
                      ls -la
                      echo "Contents of target directory:"
                      ls -la target/ || echo "Target directory not found"
                      # Ensure the Dockerfile can find the JAR file
                      cp -r target/ $(pwd) || echo "Failed to copy target directory"
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: false
                    connectorRef: dockerhub_connector
                    repo: jhttp
                    tags:
                      - latest
                    dockerfilePath: Dockerfile
                    context: .
                    buildArgs:
                      JAR_FILE: target/jhttp-1.0-SNAPSHOT.jar
                  timeout: 10m
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
